### ISSUE TITLE
I2C documentation

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#101]
Write a page on the wiki explaining our I2C functions and how they can be used from the command-line tool.  Point to the command-line tool as sample code for the I2C Python API.  See the Bus Pirate I2C guide for inspiration.

**Comment by mossmann** [comment]
more inspiration: https://www.totalphase.com/support/articles/200349176-7-bit-8-bit-and-10-bit-I2C-Slave-Addressing

**Comment by GravesJake** [comment]
https://github.com/greatscottgadgets/greatfet/wiki/greatfet_i2c
