### ISSUE TITLE
simultaneous logic analysis

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#108]
Support running logic analysis while simultaneously doing other things such as I2C or SPI.

**Comment by ktemkin** [comment]
Should be supported once the SGPIO content is merged; (and you can have multiple shells open as of libgreat master).

**Comment by ktemkin** [comment]
This is merged; this _should_ work, as long as the sample rate is sufficiently low as to allow other USB traffic. :)
