### ISSUE TITLE
Chipcon debug command-line tool

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#116]
Support flash dump, flash erase, flash write, flash verify, peek, and poke.

**Comment by grvvy** [comment]
This was included in #335

**Comment by Qyriad** [comment]
#335 included a Python API for Chipcon debugging. This issue is about a command-line tool. i.e.:
```bash
$ greatfet chipcon flash -w file.bin
```

**Comment by grvvy** [comment]
That's right, I misremembered.

**Comment by Qyriad** [comment]
Implemented in #348.

**Comment by atlas0fd00m** [comment]
why does this not work with current pip installed version?

```$ greatfet chipcon flash -w file.bin
ERROR: Unsupported subcommand 'chipcon'.
Check to ensure the package providing the subcommand is installed.
```

**Comment by atlas0fd00m** [comment]
oh, i see, i thought this was added 2 years ago, didn't see that it was just merged in 2 weeks ago.
thanks all!
@
