### ISSUE TITLE
GPIO rewrite

### ISSUE THREAD

**Issue by ktemkin** [greatscottgadgets/greatfet#135]
The GPIO drivers need a re-write to avoid issues -- this is needed for the factory test jig.

**Comment by mossmann** [comment]
It would be nice to be able to set the pin output state before setting the direction.  Currently it is impossible from Python to switch from input to output without driving the output low at least briefly.

**Comment by mossmann** [comment]
See also #138.
Claiming a pin for GPIO should make it unavailable for other functions and vice versa.
