### ISSUE TITLE
What does "Firmware functions to replace" mean?

### ISSUE THREAD

**Issue by emb4fun** [greatscottgadgets/greatfet#157]
Hello,

I found in the wiki the following point: "Firmware functions to replace"?
What exactly does it mean, what is the intention here?
E.g. in case of "nvic_set_priority" there exist some CMSIS functionality from
ARM which can be used.

The code:

nvic_set_priority(NVIC_USB0_IRQ, 254);

can be replaced by:

NVIC_SetPriority(NVIC_USB0_IRQ, 254);

But the most ARM cores I know does not have a priority range of 8 bit.
The most have 4 or 5 bit. In case you are using the LPC4330, the CPU
has only 8 programmable interrupt priority levels, that mean only 3 bits.

Therefore a priority of 254 does not make sense here.

Best regards,
Michael

**Comment by dominicgs** [comment]
I replied to this question on the mailing list, here: https://pairlist3.pair.net/pipermail/greatfet/2018-October/000015.html
