### ISSUE TITLE
NXP Xplorer board files need updates

### ISSUE THREAD

**Issue by ktemkin** [greatscottgadgets/greatfet#165]
The NXP Xplorer host board files need to be updated to work with libgreat. This shouldn't be much work, but needs to be tested by someone with an accessible Xplorer board. :)

Related: #85, #164

**Comment by Renaud-Pagin** [comment]
I have a Xplorer board !

Ready for testing and making report / debug !

**Comment by ktemkin** [comment]
At this point, this and #164 are essentially the same issue; so I'm closing this one in favor of using #164 to track the issue.
