### ISSUE TITLE
standardize on 7-bit I2C addresses in software

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#202]
Ensure that all command-line options and output and python/USB API parameters and return values use 7-bit address format (not 8-bit) by default.

For background info see:
https://www.totalphase.com/support/articles/200349176-7-bit-8-bit-and-10-bit-I2C-Slave-Addressing

**Comment by mossmann** [comment]
Also please update the greatfet_i2c wiki page:
https://github.com/greatscottgadgets/greatfet/wiki/greatfet_i2c

I updated the other wiki pages but didn't want to touch that one until the tool is updated.

**Comment by GravesJake** [comment]
Resolved by fce6c61

**Comment by GravesJake** [comment]
Wiki page updated
