### ISSUE TITLE
split libgreat into separate repo

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#207]

**Comment by dominicgs** [comment]
https://github.com/greatscottgadgets/libgreat

**Comment by ktemkin** [comment]
Just a heads up: this is in progress, and almost complete. I’m just cleaning things up and stability testing some of the new drivers (especially the clock driver). 

I'll push a standalone `libgreat` to its own repository in the next couple of business days, and then PR replacing the in-tree version with it shortly after.

**Comment by ktemkin** [comment]
Done as of #215.
