### ISSUE TITLE
Add a WinUSB comms backend

### ISSUE THREAD

**Issue by Qyriad** [greatscottgadgets/greatfet#310]
Currently on Windows we require use of something like Zadig to install libusb-win32 for GreatFET. Instead we should just write a backend for communications over WinUSB.

**Comment by osterwood** [comment]
FYI, I just published a Python wrapper around `wdi-simple` (a command line version of Zadig and part of the libwdi repo)

https://github.com/CapableRobot/CapableRobot_USBRegister

This package includes pre-built `wdi-simple` CLI binaries and a python wrapper around them, allowing for automation of device to driver registration -- no more asking end users to download Zadig and click buttons.

**Comment by mossmann** [comment]
closing in favor of #438
