### ISSUE TITLE
I2C Python interface bug

### ISSUE THREAD

**Issue by Microsparky** [greatscottgadgets/greatfet#322]
Firmware version: v2019.9.1

When using I2C from Python shell or form script the command gf.i2c.write(0x40, 0xFE) actually transmits the address and write as expected (0x80) but then transmits 254 0x00 bytes.

The write from command line however does work.

**Comment by ktemkin** [comment]
This is a python 'quirk' -- that argument expects an argument of type `bytes`, or something that can easily be converted to bytes. `bytes(0xFE)` produces a string of 254 zeroes.

Something like `bytes(0x40, [0xfe])` or `bytes(0x40, b"\xfe")` should work the way you want it to. Let me know if you have any more trouble. :)
