### ISSUE TITLE
Running 'gf fw --auto' is not updating firmware

### ISSUE THREAD

**Issue by mbparks** [greatscottgadgets/greatfet#338]
I updated to 2019.9.1 last year.  Trying to upgrade to the latest firmware today.  Running 'gf fw --auto' is not doing anything.  Used pip to update host.  Before and after running 'gf fw --auto' the 'gf info' command shows firmware version to be 2019.9.1.  Any suggestions?  Running Windows 10 with all latest updates.

**Comment by ktemkin** [comment]
Can you run `gf info -H` for me, and paste the output here? On recent-ish host tools, this prints information about the host tools version that are being used to run commands.

**Comment by straithe** [comment]
@mbparks Are you still experiencing this issue?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
