### ISSUE TITLE
Chipcon ID 65535

### ISSUE THREAD

**Issue by pickeditmate** [greatscottgadgets/greatfet#351]
I am testing out the newest addition of greatfet chipcon CLI tool. 
When issuing a gf chipcon --chip-id I'm getting a readout of "Chip ID : 65535" which seems rather strange, so wondering if someone else who has an imme or yardstick can test theirs to see if they get the same. 

My wiring is J2.37 to !rst, 
J2.39 to DD, 
J2.38 to DC, 
power and ground to +2.5V and gnd respectively.

**Comment by grvvy** [comment]
Testing on yardstick I get `chip_id = 4355`. ~~Make sure to call `chipcon.debug_init()` before doing anything else.~~ Sorry that's for when you're working inside of `gf shell`.

**Comment by grvvy** [comment]
My setup: 
```
J1.01 -> GND
J1.02 -> 3v3
J1.37 -> DD
J1.39 -> DC
J1.40 -> RESET
```
[GPIO pin definitions](https://github.com/greatscottgadgets/greatfet/blob/master/firmware/common/swra124.c#L13) along with their [pin mappings on the board](https://github.com/greatfet-hardware/azalea#j1-neighbor1-pinout).

**Comment by pickeditmate** [comment]
Thank you Jake, chip ID is now 259. I was using the pin mappings for the begonia neighbour https://github.com/greatfet-hardware/begonia directly. 

Thanks for the help and for the links too as I struggle finding which pins to use other than what's on the cheat sheet picture and silk screen. 

I wonder whether it's worthwhile having the pins as a comment in the swra library for others to not make the same mistake?
