### ISSUE TITLE
USB error when running "gf info" in a VM

### ISSUE THREAD

**Issue by potto216** [greatscottgadgets/greatfet#357]
I receive a USB error when I run `gf info` which causes an exception and the code to end when running in a VM.  The error is usb.core.USBError: [Errno 5] Input/Output Error.

I am running the software in a VMWare VM using Ubuntu 18-4-4 and I think this is related to
a similar VMWare issue https://github.com/greatscottgadgets/greatfet/issues/250

I verified that the GreatFET is visible by the VM with `lsusb`. The output of the command is in [lsusb_greatfet.txt](https://github.com/greatscottgadgets/greatfet/files/5507501/lsusb_greatfet.txt)

The full output of the error when running `gf info` is in [gf_info_output.txt](https://github.com/greatscottgadgets/greatfet/files/5507502/gf_info_output.txt)
This error occurs on
```
 File "/home/user/anaconda3/lib/python3.7/site-packages/pygreat/comms_backends/usb.py", line 354, in execute_raw_command
    self.LIBGREAT_REQUEST_NUMBER, self.LIBGREAT_VALUE_EXECUTE, flags, to_send, timeout)

351                     self.device.ctrl_transfer(
352                         usb.ENDPOINT_OUT | usb.TYPE_VENDOR | usb.RECIP_ENDPOINT,
353                         self.LIBGREAT_REQUEST_NUMBER, self.LIBGREAT_VALUE_EXECUTE, flags, to_send, timeout)
354
```

The full output of the error when additional debug information is selected (`LIBUSB_DEBUG=4 and USB_DEBUG=debug`) is in the file: [gf_info_output_debug_verbose.txt](https://github.com/greatscottgadgets/greatfet/files/5507503/gf_info_output_debug_verbose.txt).

In the above output file I had also modified "pygreat/comms_backends/usb.py" to print out additional information around line 354. The statements I added were:
```python
print("****************start ctrl_transfer************",flush=True);
print(f"flags = {flags}, to_send = {to_send}, timeout = {timeout}",flush=True);
print("****************end ctrl_transfer************",flush=True);
```

Their output is visible in "gf_info_output_debug_verbose.txt"

I researched the error and found a similar issue also posted on the pyusb repo (https://github.com/pyusb/pyusb/issues/216). They felt it was a VMWare issue however I could not find details supporting that. I use VMWare for the HackRF, RTL, LimeSDR, and AirSpy and have never had a problem with their USB pass though. If it is a problem with VMWare I would like to get additional details so I can work with VMWare to fix the issue.

The USB error has occurred with Python 3.6, 3.7, and 3.8 both using Anaconda installs and without. 

On the same computer that runs VMWare I was able to connect to the GreatFET One on the native Windows 10 install and also update the firmware. The firmware update did not change the error message in the Linux VM.

I was wondering what I should do next for troubleshooting? 

I'm not sure if this is related, but I did find this issue interesting (https://github.com/pyusb/pyusb/issues/126) because it dealt with different behavior from ctrl_transfer with Linux and Windows backends. Since I'm running a VM Linux on a Windows 10 machine I didn't know if this could have any influence.

Thanks again for the hardware, software, and talks your company has provided.
[lsusb_greatfet.txt](https://github.com/greatscottgadgets/greatfet/files/5507501/lsusb_greatfet.txt)
[gf_info_output.txt](https://github.com/greatscottgadgets/greatfet/files/5507502/gf_info_output.txt)
[gf_info_output_debug_verbose.txt](https://github.com/greatscottgadgets/greatfet/files/5507503/gf_info_output_debug_verbose.txt)

**Comment by potto216** [comment]
Just seeing if there are any suggestions on what I should do to further debug the issue?

**Comment by potto216** [comment]
Let me know if there is any way I can help with this.  Thanks for looking at it!

**Comment by ttimasdf** [comment]
Use DFU mode to flash rom works fine(`greatfet_firmware -V greatfet_usb.bin`), maybe some bug in the usb stack?

**Comment by ttimasdf** [comment]
Run USBpcap on a Windows host, I see all packets respond with `USBD_STATUS_XACT_ERROR` after the host invoked `URB_FUNCTION_SELECT_CONFIGURATION` with index=0. And in Linux guest, we could see an `EPROTO` response.

![image](https://user-images.githubusercontent.com/2762704/138672009-db2d4896-9b60-4e42-9402-e189ae5bba85.png)

![image](https://user-images.githubusercontent.com/2762704/138672244-6e7c45fe-4962-4835-b4a8-2daf6c560de3.png)

![image](https://user-images.githubusercontent.com/2762704/138672408-f03ea914-b550-4bf9-a62f-5c444f20c0ed.png)

The host runs Windows 11 with VMWare Workstation 16.2.0 connecting to a remote VM on ESXi, if that matters. Guest OS is Kali Linux 2021.3.

**Comment by patois** [comment]
I've had partial success with a Linux VM running inside VMWare Workstation by editing its .vmx configuration file. Shutting down the VM, then adding the following line and booting the VM again will make GreatFET devices recognizable but still not fully functional (there will be either exceptions or misbehavior depending on the gf script you're running).

`usb.generic.skipsetconfig = "TRUE"`

It may be worth trying/adding other .vmx configuration settings, some can be found on [sanbarrow.com](https://sanbarrow.com/vmx.html), others on [this page](https://s3.amazonaws.com/virtuallyghetto-download/hidden_vmx_params.html). Good luck!

edit: just found ["Troubleshooting USB devices using USB quirks in Fusion"](https://kb.vmware.com/s/article/1025256), in which further settings are explained that allow device quirks to be set individually by specifying vid and pid of the device. This way, we can avoid the setup step to be skipped for all USB devices, generically. Unfortunately, I still did not manage to get my GreatFETs to fully work with any of the combinations mentioned in the article. Hopefully, it can still help in narrowing down further problem causes.

**Comment by potto216** [comment]
Thanks, I'll try that out.

**Comment by robvinson** [comment]
Adding this line to my VMWare VMs .vmx file got the greatfet working for me:

```
usb.quirks.device0 = "0x1d50:0x60e6 allow, skip-reset, skip-refresh, skip-setconfig"
```

**Comment by potto216** [comment]
Thanks so much @robvinson !!!!! This worked for me also. I'm going to close the issue because this is a great solution.

**Comment by meeas** [comment]
Awesome work @robvinson !!!  That has plagued my Black Hat course for the last few years, forcing everyone on Windows to use VirtualBox.  The VMware works just fine without modification on Mac and Linux, just not Windows.  And all other virtualization software on Windows works fine, just not VMware................until now.  :-)
