### ISSUE TITLE
Possible compatibility issue with VMware on Windows 10

### ISSUE THREAD

**Issue by meeas** [greatscottgadgets/greatfet#389]
K, this has been a strange one.  For some reason, trying to pass GreatFET through VMware Workstation/Player (last few versions) from a Windows Host to a Linux virtual machine is resulting in I/O issues.  VMware can see and allows me to connect GreatFET to my Linux VM, `lsusb` can see the GreatFET device, and `dmesg` shows it gets registered with `udev` correctly.  However when I try to use the GreatFET commands, it throws errors.  Sorry, I will try to update this issue later with the exact error.  Using the same hardware and same VM works fine with:

- Windows 10 + VirtualBox
- Mac OS + VMware Fusion
- Mac OS + VirtualBox
- Linux + VMware
- Linux + VirtualBox

The only combination that doesn't seem to work is Windows 10 + VMware, which seems to point at a possible I/O conflict between GreatFET and VMware, which just seems strange to me.  Perhaps a timing/race condition issue?  I have yet to analyse the USB traffic between a working and non-working combination, but for now I'm hoping to reach out to a larger audience to see if anyone else has had success with getting Windows 10 + VMware to work for them.

I've tried this on multiple machines in my courses with my students, on multiple versions of Windows 10 and the last 2-3 versions of VMware Workstation and Player.

**Comment by meeas** [comment]
This seems to be connected to #250 and #357 

If you are trying to use GreatFET on a host machine running Windows 10, my suggestion is to use VirtualBox to host your Linux VM as it works without issue.  Just make sure to the Oracle Extension Pack on your host and enable USB 3.0 support in your VM.

**Comment by straithe** [comment]
Thank you for the tip! We appreciate it. I'm going to close this issue as you have found a solution.
