### ISSUE TITLE
gf = GreatFET() fails with libusb1 available

### ISSUE THREAD

**Issue by williamdeeks** [greatscottgadgets/greatfet#393]
Hi,

I need to use libusb1 to support another device, but in Python calling:
`gf = GreatFET()`
results in:
`Process finished with exit code -1073741819 (0xC0000005)`

when libusb1.dll is available in my path (I'm on windows).

I believe GreatFET relies on functionality in libusb0 which doesn't exist in libusb1, but doesn't specify this when calling usb.core.find()

I forced PyUSB to use libusb0 by modifying usb.core.find. Of course, this then breaks PyUSB for my other device that requires the newer libusb1.

Please could the GreatFET library be updated to specify the libusb0 backend, or update it to work with libusb1? I can see there is a fork with support for libusb1, but it's quite far behind the main branch.

Thanks.

**Comment by straithe** [comment]
Have you been able to get this to work with libusb0? If so, what modifications did you make to do so? 

We expect GreatFET to work with libusb1. Our primary development platform is Ubuntu, so there may be an unexpected Windows issue that may need to be sorted out.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
