### ISSUE TITLE
Hack RF Not Found Only 3V3 light is on

### ISSUE THREAD

**Issue by 0xGSMonkey** [greatscottgadgets/greatfet#397]
I don't think it is the USB cable I have used 4 different USB cables and all of them show the 3V3 light as being the only light that shows. I am not sure what happened. I connected PIn 11 and PIn 18 on Expansion Interface 22 without reading the docs. Did this fry my hackrf one? D:

**Comment by gozu42** [comment]
is this about a greatfet? or a hackrf? or trying to run a hackrf through a greatfet?
(depending on the answer, you may be in the wrong project/tracker)

**Comment by 0xGSMonkey** [comment]
Wrong Project. Sorry! It is about the HackRF One
