### ISSUE TITLE
Documentation needs updating for Logic Analysis

### ISSUE THREAD

**Issue by pickeditmate** [greatscottgadgets/greatfet#399]
https://greatscottgadgets.github.io/greatfet-tutorials/logic-analysis.html
shows gf.spi.transmit("GreatFET") bot doing this on Python3 errors out. 

Instead I used gf.spi.transmit(b"\x88\x88\x88\x88")

**Comment by straithe** [comment]
Thank you. I will add a documentation update to my to do list.

**Comment by unixb0y** [comment]
> Thank you. I will add a documentation update to my to do list.

Ping; it's still unchanged.

**Comment by antoinevg** [comment]
Fixed in: https://github.com/greatscottgadgets/greatfet-tutorials/pull/20
