### ISSUE TITLE
MSP430 compatibility

### ISSUE THREAD

**Issue by codehero** [greatscottgadgets/greatfet#406]
Is there a documented list of MSP430 processors compatible with GreatFET?

**Comment by mossmann** [comment]
There is not a documented list. As far as I know, the GreatFET MSP430 JTAG function should work with any 16-bit MSP430 but not with 20-bit MSP430X.

**Comment by codehero** [comment]
OK thanks. My target processors are the FR2422 and the FR5739 so I am not sure if the GreatFET would work with those.
