### ISSUE TITLE
Unreadable tables in offline documentation

### ISSUE THREAD

**Issue by brianredbeard** [greatscottgadgets/greatfet#408]
While reading the [PDF] (pg 22) of the GreatFET documentation I ran into a bit of a challenge in understanding the verb structure:  :rofl: 
![image](https://user-images.githubusercontent.com/57542/197324396-7edbe968-c824-479d-b340-9f88eb560f06.png)

Methinks that this may be a regression related to #376 (the migration to Sphinx for documentation).

[PDF]: https://greatfet.readthedocs.io/_/downloads/en/latest/pdf/

**Comment by straithe** [comment]
Thanks for letting us know! I'll fix this.
