### ISSUE TITLE
Release GreatFET 2024.0.0

### ISSUE THREAD

**Issue by unixb0y** [greatscottgadgets/greatfet#417]
As I realized in https://github.com/greatscottgadgets/greatfet/issues/415, I believe a new release is more than overdue.

```[tasklist]
### Issues
- [ ] https://github.com/greatscottgadgets/greatfet/issues/327
- [ ] https://github.com/greatscottgadgets/greatfet/issues/428
- [ ] #399
- [ ] https://github.com/greatscottgadgets/greatfet/issues/415
- [ ] https://github.com/greatscottgadgets/greatfet/issues/378
- [ ] https://github.com/greatscottgadgets/greatfet/issues/373
```

```[tasklist]
### Review, merge or close outstanding pull requests
- [ ] https://github.com/greatscottgadgets/libgreat/pull/33
- [ ] https://github.com/greatscottgadgets/greatfet/pull/418
- [ ] https://github.com/greatscottgadgets/greatfet/pull/413
- [ ] https://github.com/greatscottgadgets/greatfet/pull/423
- [ ] https://github.com/greatscottgadgets/greatfet/pull/426
- [ ] https://github.com/greatscottgadgets/greatfet/pull/405
```

**Comment by unixb0y** [comment]
ping

**Comment by straithe** [comment]
Thank you for the ping. We have seen this request and have a couple of PRs and other changes to make before we cut a new release. We really appreciate your patience.

**Comment by unixb0y** [comment]
Still no release, it's been 11 months since creation of this issue. And the bug that doesn't even let you use the device (if you install `greatfet` from `pip`) is still there, too, despite the issue having been closed today.
https://github.com/greatscottgadgets/greatfet/issues/415

**Comment by antoinevg** [comment]
Just a few things left to do. I'll be pushing a release soon.

**Comment by antoinevg** [comment]
Released: https://github.com/greatscottgadgets/greatfet/releases/tag/v2024.0.0
