### ISSUE TITLE
MSP430 jtag support

### ISSUE THREAD

**Issue by dominicgs** [greatscottgadgets/greatfet#81]
Use GoodFET as a reference

**Comment by dominicgs** [comment]
https://github.com/travisgoodspeed/goodfet/tree/master/firmware/apps/jtag

**Comment by mossmann** [comment]
This is mostly done (in firmware) except that there is a bug that causes a particular word to be written incorrectly to when flashing.

**Comment by dominicgs** [comment]
Don't forget to rewrite the tool description in the help text.  Also, add a wiki page to document it.

**Comment by mossmann** [comment]
Other than Python2 compatibility (#257), my testing indicates that things work.
