### ISSUE TITLE
one-shot ADC

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#93]
We currently have a method of streaming samples from the internal ADC in the MCU, but I would like a Python function on the host that retrieves a single sample. This function should additionally be implemented in greatfet_adc.py as an alternative to continuous streaming.

**Comment by dominicgs** [comment]
There's a USB function for it here:
https://github.com/greatscottgadgets/greatfet/blob/master/firmware/greatfet_usb/usb_api_adc.c#L29

I think it might have a bug or two in it.

**Comment by GravesJake** [comment]
```
data = device.vendor_request_in(vendor_requests.ADC_READ, length=2)
print('%d' % (data[1] << 8 | data[0]))
```
For testing the ADC value
