### ISSUE TITLE
I2C scan

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/greatfet#95]
Brute force I2C addresses and report every address that results in an acknowledgement from a slave. The ACK indication can be found in the I2C status register. The scan function should be accessible from firmware and from the Python API.

**Comment by GravesJake** [comment]
Resolved by da4806ddbeca66d079f0695005ce4085830d90b3

**Comment by mossmann** [comment]
assigned to self to test and approve

**Comment by GravesJake** [comment]
fce6c61 v2

**Comment by ktemkin** [comment]
Closed, as this is now working (thanks, @GravesJake!). Enhancements to this have been created as separate issues.
